name: Get Transloc Data

on:
  schedule:
    # Runs at 11:30 AM UTC which is 6:30 AM CST/CDT
    - cron:  '45 4 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz
        pip install sys
        # Add any other dependencies here

    - name: Run the script
      run: |
        # Run your script here
        python main.py
